apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: redis-scaledobject
  namespace: default
  labels:
    deploymentName: dummy
spec:
  maxReplicaCount: 4
  pollingInterval: 5  # Optional. Default: 30 seconds
  cooldownPeriod:  5 # Optional. Default: 300 seconds
  scaleTargetRef:
    deploymentName: dummy
  triggers:
    - type: redis
      metadata:
        address: REDIS_ADDRESS
        listName: default
        listLength: "10"